credentials:
  usernames:
    rizwana:
      email: rizwana@example.com
      name: Rizwana Banu
      password: "..........................." # hashed password

cookie:
  name: travel_app_auth
  key: some_random_signature_key
  expiry_days: 30

preauthorized:
  emails:
    - rizwana@example.com
